services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: dinacare
      POSTGRES_USER: dinacare_user
      POSTGRES_PASSWORD: dinacare_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dinacare
      SPRING_DATASOURCE_USERNAME: dinacare_user
      SPRING_DATASOURCE_PASSWORD: dinacare_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: