spring:
  application:
    name: DinaCare

#  datasource:
#    url: jdbc:postgresql://localhost:5432/dinacare
#    username: postgres
#    password: admin123
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: 8

  flyway:
    enabled: true
    locations: classpath:db/migration
